# Generated by Django 5.2.7 on 2026-10-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='chatbot.business'),
        ),
    ]
